### PR TITLE
Changing default sort order to alphabetical

### PR DESCRIPTION
**Pull request by NickBusey**
## Describe the changes you made

I changed the default sort order for documents to be by name instead of created date.

## Why were these changes necessary/desired?

Same reason we changed the sort of the tags on the left, much easier to scan.

If having it sortable by most recent is also still desirable, I'll look into adding a sort mode toggle potentially? But in general I find alphabetical to be a much more useful default view.

## How can the changes be tested?

Look at your document order on the main page.

## Did you already test the changes?

Yup, As are before Bs.

### CODE REVIEW

**Comment by thomasbrueggemann** [comment]
That's a good point. It's very usecase dependent. For my usecase of paper-invoice-tracking the order by created date is great. 
I think a toggle button would be ideal here, including storing the user preference in localstorage.

**Comment by NickBusey** [comment]
Alright, I've added a select box, and it works, kinda. Once you change the setting you have to select and then un-select a tag or correspondent to get it to re-render the documents. Not sure how to fix that yet..

**Comment by thomasbrueggemann** [comment]
I can take a look at it next weekend.

**Comment by NickBusey** [comment]
Alright this should be good to go, other than the horrendous commit history.

**Comment by NickBusey** [comment]
Alright, well daniel has decided that the alpha ordering works as expected (I disagree) but since it looks like no progress will be made on the internal issue referenced above, this issue looks to be as ready as it'll ever be.

**Comment by thomasbrueggemann** [comment]
@NickBusey I don't have time to maintain this project anymore, so I gave you commit access to make any changes you'd like. It would be nice to follow the style used by the rest of the code.

**Pull request closed without merging**
