### PR TITLE
fixed sidebar filter API calls

### PR DESCRIPTION
**Pull request by tsia**
## Describe the changes you made

I changed the API Parameters for the Sidebar Filters

## Why were these changes necessary/desired?

Because they didn't work

## How can the changes be tested?

You have to ...

## Did you already test the changes?

I tested ...

### CODE REVIEW

**Comment by mipmip** [comment]
👍

**Comment by thomasbrueggemann** [comment]
Okay, @tsia , to understand the changes you made: Are these new query parameters within Paperless? How do these changes raise the minimum required version of Paperless?

**Comment by tsia** [comment]
i just noticed that the filters don't work anymore.
i had a look how the filter works that are available when browsing to /api/documents/.
i'm not sure when this changed. i assume it happened with an update of the django REST framework.

**Comment by thomasbrueggemann** [comment]
@tsia I don't have time to maintain this project anymore, so I gave you commit access to make any changes you'd like. It would be nice to follow the style used by the rest of the code.

**Pull request merged**
